apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visitor-ingress
spec:
  rules:
  - host: visitor.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: visitor-service
            port:
              number: 80