apiVersion: v1
kind: Service
metadata:
  name: visitor-counter-service
spec:
  selector:
    app: visitor-counter
  type: ClusterIP       # Change from nodeport to CLusterIP so i can organise dns
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000  # Pick a free port on your host machine