apiVersion: v1
kind: Service
metadata:
  name: visitor-counter-service
spec:
  selector:
    app: visitor-counter   # must match your pod label
  ports:
    - protocol: TCP
      port: 80             # Ingress will connect here
      targetPort: 8000     # FastAPI container port
  type: ClusterIP