apiVersion: v1
kind: Service
metadata:
  name: visitor-counter-service
spec:
  selector:
    app: visitor-counter
  type: NodePort       # For local Docker Desktop / Minikube
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000  # Pick a free port on your host machine