apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visitor-counter
  template:
    metadata:
      labels:
        app: visitor-counter
    spec:
      containers:
      - name: visitor-counter
        image: duge331/visitor-counter:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: aws-credentials
        - configMapRef:
            name: visitor-config